Repository meilisearch/heed, pull requests merged in 2023-07, with the labels that each got.

#174 RwTxn + RoTxn documentation improvement.
  heed/src/env.rs
  heed/src/txn.rs
Labels: documentation

#194 Rename and document the `MDB_NOTLS` feature
  heed/Cargo.toml
  heed/src/env.rs
  heed/src/txn.rs
Labels: bug, documentation, security

#193 Rename and document the `MDB_NOTLS` feature
  heed/Cargo.toml
  heed/src/env.rs
  heed/src/txn.rs
Labels: documentation, security
