Repository meilisearch/heed, pull requests merged in 2023-08, with the labels that each got.

#200 Add support for every database flags
  heed-types/src/lazy_decode.rs
  heed-types/src/lib.rs
  heed/Cargo.toml
  heed/examples/all-types-poly.rs
  heed/examples/cursor-append.rs
  heed/src/cursor.rs
  heed/src/database.rs
  heed/src/db/mod.rs
  heed/src/db/uniform.rs
  heed/src/env.rs
  heed/src/iteration_method.rs
  heed/src/iterator/iter.rs
  heed/src/iterator/mod.rs
  heed/src/iterator/prefix.rs
  heed/src/iterator/range.rs
  heed/src/lib.rs
  heed/src/mdb/lmdb_ffi.rs
  heed/src/mdb/lmdb_flags.rs
  lmdb-master-sys/Cargo.toml
  lmdb-master-sys/bindgen.rs
  lmdb-master-sys/src/bindings.rs
  lmdb-master-sys/src/lib.rs
  lmdb-master-sys/tests/lmdb.rs
  lmdb-master-sys/tests/simple.rs
Labels: breaking

#204 Add `rmp-serde` support to heed-types.
  .github/workflows/rust.yml
  heed-types/Cargo.toml
  heed-types/src/lib.rs
  heed-types/src/serde_rmp.rs
  heed/Cargo.toml
  heed/examples/rmp-serde.rs
Labels: enhancement

#203 Fix the `serde-json` feature declaration of heed
  heed/Cargo.toml
Labels: bug
